### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AminulBD** [AminulBD/dotbd-domain-checker#1]
- [ ] Configuraable options
- [ ] Validation extensions
- [ ] Create docs for how to use
- [ ] Create docs for WHMCS
- [ ] Create docs for server setup 
- [ ] Remove invalid data from whois section when have a invalid extension
